param(
    [string]$TargetDrive = "C:",
    [string]$OutputDir = "C:\Temp\Cerberus_Evidence"
)

# --- CONFIGURATION ---
$ErrorActionPreference = "SilentlyContinue"
$ToolsDir = ".\Tools"
# KAPE usually resides in a subfolder, e.g. Tools\KAPE\kape.exe
$KapeExe = "$ToolsDir\KAPE\kape.exe" 

# KAPE Configuration
# Target: What files to grab? (KapeTriage = Standard Forensics)
$KapeTarget = "KapeTriage"
# Module: How to process them? (!EZParser = Run all Zimmerman Tools -> CSV)
$KapeModule = "!EZParser"

# Create Output Directory
if (-not (Test-Path $OutputDir)) {
    New-Item -Path $OutputDir -ItemType Directory -Force | Out-Null
}

Write-Host "[-] Starting Cerberus KAPE Collection..." -ForegroundColor Cyan
Write-Host "    Target: $TargetDrive" -ForegroundColor Gray
Write-Host "    Output: $OutputDir" -ForegroundColor Gray

# --- HTML REPORTING ENGINE (Ported from WinArtifacts) ---
function Generate-HTMLReport {
    Write-Host "`n[+] Generating Triage Report..." -ForegroundColor Yellow
    $ReportPath = "$OutputDir\Cerberus_KAPE_Report.html"

    $CSS = @"
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #121212; color: #e0e0e0; margin: 20px; }
        h1 { color: #ff5252; border-bottom: 2px solid #ff5252; padding-bottom: 10px; }
        h2 { color: #00e5ff; margin-top: 30px; border-left: 5px solid #00e5ff; padding-left: 10px; background-color: #1e1e1e; padding: 10px;}
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 0.85em; }
        th, td { padding: 8px 12px; border: 1px solid #333; text-align: left; }
        th { background-color: #2c2c2c; color: #ffffff; }
        tr:nth-child(even) { background-color: #1a1a1a; }
        tr:hover { background-color: #333; }
        .footer { margin-top: 50px; font-size: 0.8em; color: #555; text-align: center; border-top: 1px solid #333; padding-top: 10px; }
        .warning { color: #ff9800; font-style: italic; font-size: 0.8em; }
    </style>
"@

    $HTML = @"
<!DOCTYPE html>
<html>
<head>
    <title>Cerberus KAPE Report</title>
    $CSS
</head>
<body>
    <h1>CERBERUS (KAPE ENGINE) REPORT</h1>
    <p><strong>Target:</strong> $TargetDrive | <strong>Date:</strong> $(Get-Date) | <strong>Output:</strong> $OutputDir</p>
"@

    # KAPE outputs to subfolders. We must hunt for the CSVs.
    # Common file names generated by !EZParser modules
    $ArtifactsToRender = @(
        @{ File="*System_Info*"; Title="System Information"; Cols="*" },
        @{ File="*Prefetch*"; Title="Prefetch (Execution)"; Cols="SourceFilename","LastRun","RunCount" },
        @{ File="*ShimCache*"; Title="ShimCache (Execution)"; Cols="Path","LastModifiedTimeUTC","Executed" },
        @{ File="*Amcache*"; Title="Amcache (Installed Programs)"; Cols="Name","InstallDate","Publisher" },
        @{ File="*MFT*"; Title="Master File Table (Top 50)"; Cols="FileName","FileSize","Created0x10","ParentPath" },
        @{ File="*Evtx*"; Title="Event Logs"; Cols="TimeCreated","EventId","Provider","Payload" }
    )

    foreach ($Item in $ArtifactsToRender) {
        # Recurse to find the CSV because KAPE puts them in category folders (e.g. Evidence\ProgramExecution)
        $FoundFile = Get-ChildItem -Path $OutputDir -Filter "$($Item.File).csv" -Recurse | Select-Object -First 1
        
        if ($FoundFile) {
            $HTML += "<h2>$($Item.Title)</h2>"
            try {
                $RawData = Import-Csv -Path $FoundFile.FullName | Select-Object -First 50
                if ($Item.Cols -ne "*") {
                    $cols = $Item.Cols -split ","
                    $RawData = $RawData | Select-Object $cols
                }
                if ($RawData) {
                    $TableHTML = $RawData | ConvertTo-Html -Fragment -As Table
                    $TableHTML = $TableHTML -replace "<table>", "<table>"
                    $HTML += $TableHTML
                    $HTML += "<p class='warning'>* Display limited to first 50 rows. <a href='$($FoundFile.FullName)'>Open Full CSV</a></p>"
                }
            } catch {
                $HTML += "<p style='color:red'>Error parsing CSV.</p>"
            }
        }
    }

    $HTML += @"
    <div class='footer'>
        Generated by Cerberus Triage Toolkit | Engine: KAPE
    </div>
</body>
</html>
"@

    $HTML | Out-File -FilePath $ReportPath -Encoding UTF8
    Write-Host "    [+] HTML Report Generated: $ReportPath" -ForegroundColor Green
}

# --- EXECUTION ---

if (Test-Path $KapeExe) {
    Write-Host "    [>] KAPE Binary Found." -ForegroundColor Green
    
    # Arguments for KAPE:
    # --tsource = Source Drive (C:)
    # --tdest = Destination for collected files
    # --tflush = Delete dest if exists (Clean start)
    # --target = KapeTriage (Standard Collection)
    # --module = !EZParser (Process everything to CSV)
    # --gui = False (Command line mode)
    
    $KapeArgs = "--tsource $TargetDrive --tdest `"$OutputDir`" --target $KapeTarget --module $KapeModule --tflush --gui"
    
    Write-Host "    [>] Launching KAPE (This may take 5-10 minutes)..." -ForegroundColor Cyan
    
    # Run KAPE using Start-Process to ensure we wait for it
    $Process = Start-Process -FilePath $KapeExe -ArgumentList $KapeArgs -Wait -NoNewWindow -PassThru
    
    if ($Process.ExitCode -eq 0) {
        Write-Host "    [+] KAPE Collection Complete." -ForegroundColor Green
        
        # Run Reporting
        Generate-HTMLReport
    } else {
        Write-Host "    [!] KAPE exited with errors (Code: $($Process.ExitCode))." -ForegroundColor Red
        Write-Host "        Check the KAPE logs in the output folder." -ForegroundColor Yellow
    }

} else {
    Write-Host "    [!] KAPE not found at: $KapeExe" -ForegroundColor Red
    Write-Host "        Please ensure 'kape.exe' is in '.\Tools\KAPE\'" -ForegroundColor Yellow
}